---
# tasks file for vector-role
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "./vector.deb"
- name: Install vector package
  become: true
  ansible.builtin.apt:
    deb: vector.deb
  notify: Start vector service
- name: Copy file vector.yaml
  become: true
  ansible.builtin.copy:
    src: vector.yaml
    dest: /etc/vector/vector.yaml
    mode: '0644'
  notify: Start vector service